---
- name: Set variables
  set_fact:
    "{{ inner_item.key }}": "{{ inner_item.value }}"
  with_dict: "{{ item }}"
  loop_control:
    loop_var: inner_item

- name: Ensure Nginx is configured
  include_role:
    name: nginx
    allow_duplicates: False

- name: Install dhparam.pem
  copy:
    src: dhparam.pem
    dest: /etc/nginx/dhparam.pem
    owner: root
    group: root
    mode: 0644
    force: no
  when: use_ssl

- name: Create folder for external nginx locations
  file:
    path: /etc/nginx/locations.d/{{ site_url }}
    state: directory
    owner: root
    group: root
    mode: 0755

# TODO: Remove the absolute path from src once we can include_role
# from the source role
# https://github.com/void-ansible-roles/jekyll/issues/8
- name: Install site descriptor
  template:
    src: roles/nginx/templates/static-files.conf
    dest: /etc/nginx/sites-available/{{ site_name }}.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - nginx

- name: Enable site
  file:
    src: ../sites-available/{{ site_name }}.conf
    dest: /etc/nginx/sites-enabled/{{ site_name }}.conf
    state: link
  notify:
    - nginx

- name: Install firewall rules for resolvers
  template:
    src: roles/nginx/templates/resolvers.rules
    dest: /etc/iptables.d/nginx-resolvers.rules
    owner: root
    group: root
    mode: 0640
  notify:
    - iptables

- name: Install firewall v6 rules for resolvers
  template:
    src: roles/nginx/templates/resolvers.6rules
    dest: /etc/ip6tables.d/nginx-resolvers.6rules
    owner: root
    group: root
    mode: 0640
  notify:
    - iptables
